// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_read_copc_header
Rcpp::List cpp_read_copc_header(std::string path_or_url);
RcppExport SEXP _copc4R_cpp_read_copc_header(SEXP path_or_urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path_or_url(path_or_urlSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_read_copc_header(path_or_url));
    return rcpp_result_gen;
END_RCPP
}
// cpp_read_copc
Rcpp::List cpp_read_copc(std::string path_or_url, Rcpp::NumericVector bbox, Rcpp::NumericVector zrange, std::string select, double max_points_dbl, bool progress);
RcppExport SEXP _copc4R_cpp_read_copc(SEXP path_or_urlSEXP, SEXP bboxSEXP, SEXP zrangeSEXP, SEXP selectSEXP, SEXP max_points_dblSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path_or_url(path_or_urlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type zrange(zrangeSEXP);
    Rcpp::traits::input_parameter< std::string >::type select(selectSEXP);
    Rcpp::traits::input_parameter< double >::type max_points_dbl(max_points_dblSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_read_copc(path_or_url, bbox, zrange, select, max_points_dbl, progress));
    return rcpp_result_gen;
END_RCPP
}
