// RcppExports_gen.cpp  –  .Call registration table only
//
// The wrapper functions are auto-generated by Rcpp::compileAttributes()
// into src/RcppExports.cpp.  This file provides the R_init_ entry point
// and registration table so the DLL self-registers its routines.

#include <Rcpp.h>

// Forward declarations of wrapper functions (defined in RcppExports.cpp)
RcppExport SEXP _copc4R_cpp_has_http_support();
RcppExport SEXP _copc4R_cpp_read_copc_header(SEXP);
RcppExport SEXP _copc4R_cpp_read_copc(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

// ── Registration table ────────────────────────────────────────────────
static const R_CallMethodDef CallEntries[] = {
    {"_copc4R_cpp_has_http_support", (DL_FUNC) &_copc4R_cpp_has_http_support, 0},
    {"_copc4R_cpp_read_copc_header", (DL_FUNC) &_copc4R_cpp_read_copc_header, 1},
    {"_copc4R_cpp_read_copc",        (DL_FUNC) &_copc4R_cpp_read_copc,        6},
    {NULL, NULL, 0}
};

RcppExport void R_init_copc4R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
