# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_read_copc_header <- function(path_or_url) {
    .Call(`_copc4R_cpp_read_copc_header`, path_or_url)
}

cpp_read_copc <- function(path_or_url, bbox, zrange, select, max_points_dbl, progress) {
    .Call(`_copc4R_cpp_read_copc`, path_or_url, bbox, zrange, select, max_points_dbl, progress)
}

