# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_write_copc <- function(filename, data, header, max_depth_input, progress) {
    invisible(.Call(`_copc4R_cpp_write_copc`, filename, data, header, max_depth_input, progress))
}

cpp_has_http_support <- function() {
    .Call(`_copc4R_cpp_has_http_support`)
}

cpp_read_copc_header <- function(path_or_url) {
    .Call(`_copc4R_cpp_read_copc_header`, path_or_url)
}

cpp_count_nodes <- function(path_or_url, bbox) {
    .Call(`_copc4R_cpp_count_nodes`, path_or_url, bbox)
}

cpp_select_nodes <- function(path_or_url, bbox, zrange, max_depth = -1L) {
    .Call(`_copc4R_cpp_select_nodes`, path_or_url, bbox, zrange, max_depth)
}

cpp_fetch_raw_chunk <- function(path_or_url, offset, byte_size) {
    .Call(`_copc4R_cpp_fetch_raw_chunk`, path_or_url, offset, byte_size)
}

cpp_fetch_raw_chunks_parallel <- function(path_or_url, offsets, sizes, n_threads = 4L) {
    .Call(`_copc4R_cpp_fetch_raw_chunks_parallel`, path_or_url, offsets, sizes, n_threads)
}

cpp_read_copc <- function(path_or_url, bbox, zrange, select, max_points_dbl, progress, max_depth = -1L, filter = "", n_threads = 4L, prefetched = NULL) {
    .Call(`_copc4R_cpp_read_copc`, path_or_url, bbox, zrange, select, max_points_dbl, progress, max_depth, filter, n_threads, prefetched)
}

